### ISSUE TITLE
Infografía  F I S

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/infografia-Brisa-4#2]
[Infografía_FIS_BrisaOsorio.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Brisa-4/files/7132342/Infografia_FIS_BrisaOsorio.pdf)

**Comment by AndreLuna6** [comment]
Calificación: 21 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
